# I-00045_S01_Frontend_prompt

**Work Item**: I-00045 — OSS Status Widget and Page: Ugly Layout and Raw JSON Rendering
**Step**: S01
**Agent**: frontend-impl

---

## ⛔ Docker is off-limits

You MUST NOT execute ANY of the following commands or any command that
changes Docker container/volume/network state:

  docker kill | docker stop | docker rm | docker restart
  docker compose up | docker compose down | docker compose restart
  docker-compose up | docker-compose down | docker-compose restart
  docker volume rm | docker volume prune
  docker system prune | docker container prune | docker image prune

The orchestration database, daemon, dashboard, and any long-lived
infrastructure containers are outside your scope. Touching them can
cause multi-hour outages and data loss (see the 2026-04-22 incident in
docs/IW_AI_Core_DB_Setup.md).

Allowed exceptions:

  1. Testcontainers spun up by pytest fixtures (they self-label and
     self-destruct via Ryuk).
  2. Read-only introspection: `docker ps`, `docker inspect`, `docker logs`.
  3. Invoking `./ai-core.sh` or `make` targets — those know which
     commands are safe.

Full policy: docs/IW_AI_Core_Agent_Constraints.md

## ⛔ Migrations: agents generate, daemon applies

Not applicable for this step (no DB changes).

---

## Input Files

- Design document: `ai-dev/active/I-00045/I-00045_Issue_Design.md`
- Template to fix: `dashboard/templates/fragments/oss_status_frame.html`
- Template to fix: `dashboard/templates/pages/project/oss.html`
- Pre-fix evidence: `ai-dev/active/I-00045/evidences/pre/I-00045-dashboard.png`
- Pre-fix evidence: `ai-dev/active/I-00045/evidences/pre/I-00045-oss-page.png`
- Conventions: `CLAUDE.md`, `dashboard/CLAUDE.md`

## Output Files

- `dashboard/templates/fragments/oss_status_frame.html` (modified)
- `dashboard/templates/pages/project/oss.html` (modified)
- `dashboard/static/styles.css` (regenerated by `make css`)
- `ai-dev/active/I-00045/reports/I-00045_S01_Frontend_report.md`

---

## Context

You are fixing five cosmetic/UX defects in two Jinja2 templates for the OSS compliance feature. **Do not implement any new features or refactor unrelated code.** Fix only what the design document describes.

Read `dashboard/CLAUDE.md` before editing:
- Tailwind CSS is prebuilt — run `make css` after editing templates that add new Tailwind classes
- Fragment templates under `templates/fragments/` must NOT extend `base.html`
- All new Tailwind classes must be concrete, not dynamically composed strings (the JIT purger scans for literal class names)

---

## Requirements

### 1. Fix raw JSON in the dashboard status pill (`oss_status_frame.html`)

**Location**: `dashboard/templates/fragments/oss_status_frame.html`, inside the `{% elif oss_enabled and scan_summary %}` branch, within the pill `<a>` element (lines ~66–68).

**Problem**: The template renders `{{ scan_summary.summary }}` which is a raw Python dict (e.g. `{'skip': 4, 'total': 73, 'must_fail': 4, ...}`).

**Fix**: Replace the raw dict render with a formatted label computed from individual dict keys. The `summary_json` dict contains:
- `must_pass`, `should_pass`, `may_pass` → total passing
- `must_fail` → critical failures
- `should_fail` → warnings

Display format: `"N passed · N critical · N warnings"`. Rules:
- Total passed = `(summary.must_pass or 0) + (summary.should_pass or 0) + (summary.may_pass or 0)`
- Always show "N passed"
- Show "· N critical" only if `must_fail > 0`
- Show "· N warnings" only if `should_fail > 0`

In Jinja2, `scan_summary.summary` is a dict, so access keys with `.get()` or the `summary['key']` syntax. Use Jinja2's `namespace` or intermediate `set` variables to compute totals cleanly:

```jinja2
{% if scan_summary.summary %}
  {% set s = scan_summary.summary %}
  {% set passed = (s.get('must_pass', 0) + s.get('should_pass', 0) + s.get('may_pass', 0)) %}
  {% set critical = s.get('must_fail', 0) %}
  {% set warnings = s.get('should_fail', 0) %}
  <span>
    {{ passed }} passed
    {%- if critical > 0 %} · {{ critical }} critical{% endif %}
    {%- if warnings > 0 %} · {{ warnings }} warnings{% endif %}
  </span>
{% endif %}
```

**Verify**: After the change, no part of the page should contain the strings `must_fail`, `{'skip'`, or `'total'` in the rendered HTML for the dashboard route.

### 2. Make "OSS STATUS" heading a clickable link (`oss_status_frame.html`)

**Location**: `oss_status_frame.html`, the `<h3>` element (~line 7) inside the `flex items-center justify-between mb-3` row.

**Fix**: Wrap the heading text in an `<a>` that links to the OSS page:

```jinja2
<a href="/project/{{ current_project.id }}/oss"
   class="text-sm font-semibold text-muted-foreground uppercase tracking-wide hover:text-foreground transition-colors">
  OSS Status
</a>
```

Keep the outer `<h3>` element or replace it with the `<a>` directly — whichever keeps valid HTML (avoid `<a>` inside `<h3>` if the heading exists only for that text). The link must be present unconditionally (even when OSS is disabled — link to the OSS page regardless, it will show the install CTA there).

### 3. Move Rescan button to the heading row (`oss_status_frame.html`)

**Location**: The Rescan button is currently inside the `flex items-center justify-between` row that also contains the pill, creating a wide cluttered row.

**Fix**: Move the Rescan button (or replace it with a small refresh icon button) into the heading/title row — next to the "OSS Status" link. The existing `↻` refresh link (which does an htmx re-fetch) should become the primary rescan action in the heading row. Remove the separate Rescan button from below the pill.

The heading row should look like:
```
[OSS Status ↗]       [↻ refresh icon]
```

The `↻` link already exists: it does `hx-get="/project/{{ current_project.id }}/oss/status"` and swaps into `.oss-status-frame`. Keep that behaviour; just style it as a small icon button using a proper SVG refresh icon for clarity, and position it in the heading row. Remove the duplicate `Rescan` button that was below the pill.

When OSS is not enabled or running, still show the link in the header but omit the refresh icon.

### 4. Remove the white border from the stale warning (`oss_status_frame.html`)

**Location**: `oss_status_frame.html`, the stale banner div (~line 91):
```jinja2
class="flex items-center gap-2 text-xs text-warning bg-warning/10 border border-warning/30 rounded px-2 py-1.5"
```

**Fix**: Remove `border border-warning/30`. Keep `bg-warning/10 text-warning rounded`. The result should be a subtle amber tinted area without a box outline.

Also replace the `⚠` emoji span with a clean SVG warning icon to be consistent with the rest of the dashboard:
```jinja2
<svg class="w-3.5 h-3.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
  <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126z"/>
</svg>
```

### 5. Replace emoji status circles on the OSS page (`oss.html`)

**Location**: `dashboard/templates/pages/project/oss.html`, the "Last scan" pill section (~lines 72–109).

**Problem**: The pill uses `🔴`, `🟡`, `🟢` emoji characters as status indicators. The summary stats card further down the same page already uses CSS-styled `●` with Tailwind color classes (e.g., `text-red-700 dark:text-red-300`). Standardize the pill to match.

**Fix**: In the `{% set indicator = '🔴' %}` / `{% set indicator = '🟡' %}` / `{% set indicator = '🟢' %}` assignments for the "Last scan" pill, replace the emoji with an inline SVG circle or a CSS-styled `●` using color classes that vary by status.

Use the same pattern as the summary stats card icons at lines 132–136:
```jinja2
{# instead of: <span>{{ indicator }}</span> use: #}
{% if scan_summary.pill_color == 'red' %}
  <span class="inline-block w-2 h-2 rounded-full bg-red-500 shrink-0"></span>
{% elif scan_summary.pill_color == 'yellow' %}
  <span class="inline-block w-2 h-2 rounded-full bg-amber-500 shrink-0"></span>
{% else %}
  <span class="inline-block w-2 h-2 rounded-full bg-emerald-500 shrink-0"></span>
{% endif %}
```

Also replace the stale `⚠ stale` emoji span inside the pill (~line 107) with a small SVG warning icon or remove it from inside the pill and rely on the existing stale banner (`scan_summary.is_stale` check above).

Keep the pill's `color_class` background and `status_label` text — only replace the emoji indicator and the inline stale emoji.

### 6. Run `make css` after all template changes

After all template edits are complete, run:
```bash
make css
```

This regenerates `dashboard/static/styles.css` from the updated templates. The regenerated file must be committed alongside the template changes.

---

## Pre-flight Quality Gates (NON-NEGOTIABLE) — CR-00023

Before reporting `completion_status: complete`, run in order:

1. `make format` — auto-fixes formatting drift
2. `make typecheck` — zero errors on files you touched
3. `make lint` — zero errors

## Test Verification (NON-NEGOTIABLE)

After implementation, run:
```bash
make test-unit
```

Do NOT report `tests_passed: true` unless all unit tests pass.

---

## Subagent Result Contract

```json
{
  "step": "S01",
  "agent": "frontend-impl",
  "work_item": "I-00045",
  "completion_status": "complete|partial|blocked",
  "files_changed": [
    "dashboard/templates/fragments/oss_status_frame.html",
    "dashboard/templates/pages/project/oss.html",
    "dashboard/static/styles.css"
  ],
  "preflight": {
    "format": "ok|fixed|skipped:<reason>",
    "typecheck": "ok|skipped:<reason>",
    "lint": "ok|skipped:<reason>"
  },
  "tests_passed": true,
  "test_summary": "X passed, 0 failed",
  "blockers": [],
  "notes": ""
}
```
