"""Managed `opencode serve` subprocess lifecycle.

`OpencodeRuntime` owns starting the OpenCode HTTP/SSE server, polling its
`/global/health` endpoint until ready, terminating it cleanly, and
auto-restarting it on crash (capped at 3 restarts in any 60 s window).

The per-startup `OPENCODE_SERVER_PASSWORD` is generated by `secrets.token_urlsafe(32)`,
kept exclusively in process memory, and is *never* written to logs, stdout, stderr,
or disk by this module.
"""

from __future__ import annotations

import asyncio
import contextlib
import ctypes
import logging
import secrets
import signal
import sys
import time
from collections import deque
from typing import TYPE_CHECKING, Final

import httpx

if TYPE_CHECKING:
    from collections.abc import Callable
    from pathlib import Path

logger = logging.getLogger(__name__)

# `prctl(PR_SET_PDEATHSIG, signum)` — sent to the child when its parent dies.
_PR_SET_PDEATHSIG: Final[int] = 1
_HEALTH_TIMEOUT_SECONDS: Final[float] = 10.0
_HEALTH_POLL_INTERVAL_SECONDS: Final[float] = 0.2
_RESTART_WINDOW_SECONDS: Final[float] = 60.0
_RESTART_BACKOFF_SECONDS: Final[float] = 1.0
_MAX_RESTARTS_PER_WINDOW: Final[int] = 3
_DEFAULT_STOP_GRACE_SECONDS: Final[float] = 5.0


class OpencodeRuntime:
    """Owns the lifecycle of one `opencode serve` subprocess.

    The runtime is **single-instance**: one `OpencodeRuntime` per dashboard
    process. Sessions are managed by OpenCode itself; this object only
    starts/stops/restarts the server and exposes its base URL + password
    so the HTTP client (S02) can authenticate.
    """

    def __init__(
        self,
        repo_root: Path,
        port: int = 4096,
        bin_path: str = "opencode",
        *,
        stop_grace_seconds: float = _DEFAULT_STOP_GRACE_SECONDS,
        restart_backoff_seconds: float = _RESTART_BACKOFF_SECONDS,
        health_timeout_seconds: float = _HEALTH_TIMEOUT_SECONDS,
        health_poll_interval_seconds: float = _HEALTH_POLL_INTERVAL_SECONDS,
    ) -> None:
        self._repo_root = repo_root
        self._port = port
        self._bin_path = bin_path
        self._stop_grace_seconds = stop_grace_seconds
        self._restart_backoff_seconds = restart_backoff_seconds
        self._health_timeout_seconds = health_timeout_seconds
        self._health_poll_interval_seconds = health_poll_interval_seconds

        self._password: str = ""
        self._proc: asyncio.subprocess.Process | None = None
        self._client: httpx.AsyncClient | None = None
        self._stopping = False
        self._healthy = False
        self._watchdog: asyncio.Task[None] | None = None
        self._restart_timestamps: deque[float] = deque(maxlen=_MAX_RESTARTS_PER_WINDOW + 1)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @property
    def base_url(self) -> str:
        return f"http://127.0.0.1:{self._port}"

    @property
    def password(self) -> str:
        return self._password

    async def start(self) -> None:
        """Spawn the subprocess and wait for `/global/health` to return 200.

        Raises `RuntimeError` on health-poll timeout, or wraps the underlying
        `FileNotFoundError` if the binary cannot be located.
        """
        if not self._password:
            # Generated once per runtime instance; preserved across auto-restarts
            # so the existing client/auth header keeps working.
            self._password = secrets.token_urlsafe(32)
        self._stopping = False
        await self._spawn_once()
        if self._client is None:
            self._client = httpx.AsyncClient(
                base_url=self.base_url,
                auth=httpx.BasicAuth("opencode", self._password),
                timeout=2.0,
            )
        try:
            await self._wait_healthy()
        except RuntimeError:
            # Best effort: don't leave a zombie if the health check fails.
            await self._terminate_proc()
            await self._close_client()
            raise
        self._healthy = True
        if self._watchdog is None or self._watchdog.done():
            self._watchdog = asyncio.create_task(self._watch_for_crash(), name="opencode-watchdog")

    async def stop(self) -> None:
        """Send SIGTERM, wait up to `stop_grace_seconds`, then SIGKILL."""
        self._stopping = True
        self._healthy = False
        if self._watchdog is not None:
            self._watchdog.cancel()
            with contextlib.suppress(asyncio.CancelledError, BaseException):
                await self._watchdog
            self._watchdog = None
        await self._terminate_proc()
        await self._close_client()

    async def health(self) -> bool:
        """One-shot probe of `/global/health`. Returns True iff status is 200
        AND the runtime hasn't been marked unhealthy by the auto-restart cap.
        """
        if not self._healthy or self._client is None:
            return False
        try:
            resp = await self._client.get("/global/health")
            return resp.status_code == 200
        except (httpx.HTTPError, OSError):
            return False

    async def _close_client(self) -> None:
        if self._client is not None:
            with contextlib.suppress(BaseException):
                await self._client.aclose()
            self._client = None

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    async def _spawn_once(self) -> None:
        """Spawn the subprocess. Caller owns health-polling and watchdog setup."""
        env = self._build_child_env()
        preexec = self._build_preexec_fn()

        logger.info(
            "Starting opencode runtime on port=%s (auth: <redacted 32B token>)",
            self._port,
        )

        try:
            self._proc = await asyncio.create_subprocess_exec(
                self._bin_path,
                "serve",
                "--hostname",
                "127.0.0.1",
                "--port",
                str(self._port),
                cwd=str(self._repo_root),
                env=env,
                stdout=asyncio.subprocess.DEVNULL,
                stderr=asyncio.subprocess.PIPE,
                preexec_fn=preexec,
            )
        except FileNotFoundError as exc:
            raise FileNotFoundError(
                exc.errno or 2,
                f"opencode binary not found at '{self._bin_path}'. "
                "Set IW_CORE_OPENCODE_BIN to a valid path, or install opencode on PATH.",
                self._bin_path,
            ) from exc

    def _build_child_env(self) -> dict[str, str]:
        import os  # local import: keep top-level imports minimal

        env = dict(os.environ)
        env["OPENCODE_SERVER_PASSWORD"] = self._password
        return env

    def _build_preexec_fn(self) -> Callable[[], None] | None:
        """Return a `preexec_fn` that asks the kernel to deliver SIGTERM to the
        child when the parent dies. Linux-only; silently skipped elsewhere.
        """
        if sys.platform != "linux":
            logger.info(
                "PR_SET_PDEATHSIG unavailable on platform=%s; child won't auto-die with parent",
                sys.platform,
            )
            return None

        # Capture the constants on the closure so the child needs no imports.
        sig = signal.SIGTERM

        def _preexec() -> None:
            libc = ctypes.CDLL("libc.so.6", use_errno=True)
            libc.prctl(_PR_SET_PDEATHSIG, sig)

        return _preexec

    async def _wait_healthy(self) -> None:
        """Poll `/global/health` until 200 or timeout."""
        if self._client is None:
            raise RuntimeError("client must be created before health-poll")
        deadline = time.monotonic() + self._health_timeout_seconds
        while True:
            try:
                resp = await self._client.get("/global/health")
                if resp.status_code == 200:
                    logger.info("opencode runtime healthy on port=%s", self._port)
                    return
            except (httpx.HTTPError, OSError):
                pass

            if time.monotonic() >= deadline:
                raise RuntimeError("opencode failed to become healthy within 10s")
            await asyncio.sleep(self._health_poll_interval_seconds)

    async def _terminate_proc(self) -> None:
        """SIGTERM → grace period → SIGKILL. Also drains stderr if any."""
        proc = self._proc
        if proc is None:
            return
        if proc.returncode is not None:
            await self._drain_stderr(proc)
            return

        try:
            proc.terminate()
        except ProcessLookupError:
            await self._drain_stderr(proc)
            return

        try:
            await asyncio.wait_for(proc.wait(), timeout=self._stop_grace_seconds)
        except TimeoutError:
            logger.warning(
                "opencode did not exit within %.1fs of SIGTERM; sending SIGKILL",
                self._stop_grace_seconds,
            )
            with contextlib.suppress(ProcessLookupError):
                proc.kill()
            with contextlib.suppress(BaseException):
                await proc.wait()

        await self._drain_stderr(proc)

    async def _drain_stderr(self, proc: asyncio.subprocess.Process) -> None:
        """Drain captured stderr and log non-empty payloads at WARNING."""
        if proc.stderr is None:
            return
        try:
            chunk = await proc.stderr.read()
        except (BrokenPipeError, ConnectionResetError, OSError):
            return
        if chunk:
            text = chunk.decode("utf-8", errors="replace").strip()
            if text:
                logger.warning("opencode stderr: %s", text)

    async def _watch_for_crash(self) -> None:
        """Observe `proc.wait()`; on unexpected exit, attempt a restart.

        The restart counter is a rolling window of `_RESTART_WINDOW_SECONDS`.
        Exceeding `_MAX_RESTARTS_PER_WINDOW` flips `_healthy` to False
        permanently for this runtime instance.
        """
        while not self._stopping:
            proc = self._proc
            if proc is None:
                return
            try:
                rc = await proc.wait()
            except asyncio.CancelledError:
                raise
            except BaseException:  # noqa: BLE001 — protect the watchdog
                return

            if self._stopping:
                return
            if rc == 0:
                logger.info("opencode exited cleanly (rc=0); not restarting")
                self._healthy = False
                return

            now = time.monotonic()
            self._restart_timestamps.append(now)
            recent = [t for t in self._restart_timestamps if now - t <= _RESTART_WINDOW_SECONDS]
            if len(recent) > _MAX_RESTARTS_PER_WINDOW:
                logger.critical(
                    "OpenCode runtime is unstable; chat disabled (%d crashes within %.0fs)",
                    len(recent),
                    _RESTART_WINDOW_SECONDS,
                )
                self._healthy = False
                return

            logger.error(
                "opencode crashed with rc=%s; restart %d/%d within %.0fs window",
                rc,
                len(recent),
                _MAX_RESTARTS_PER_WINDOW,
                _RESTART_WINDOW_SECONDS,
            )
            await asyncio.sleep(self._restart_backoff_seconds)
            try:
                await self._spawn_once()
                await self._wait_healthy()
                self._healthy = True
            except (RuntimeError, FileNotFoundError, OSError) as exc:
                logger.error("opencode restart failed: %s", exc)
                self._healthy = False
                # Keep counting failed restart attempts toward the cap.
                continue
