"""add files view diff columns to work_items and step_runs

Revision ID: 1713bc13a11d
Revises: 7f1a75bb5c2d
Create Date: 2026-05-07 11:01:33.038171

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1713bc13a11d"
down_revision: str | None = "7f1a75bb5c2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "step_runs",
        sa.Column(
            "diff_text",
            sa.Text(),
            nullable=True,
            comment="Raw unified diff captured at iw step-done from the worktree",
        ),
    )
    op.add_column(
        "step_runs",
        sa.Column(
            "diff_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Parsed file metadata for this step: list of objects with keys path, status (A/M/D/R), added, removed, is_generated, is_binary, old_path",
        ),
    )
    op.add_column(
        "work_items",
        sa.Column(
            "diff_text",
            sa.Text(),
            nullable=True,
            comment="Raw unified diff of the squash commit captured at merge time",
        ),
    )
    op.add_column(
        "work_items",
        sa.Column(
            "diff_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Parsed file metadata: list of objects with keys path, status (A/M/D/R), added, removed, is_generated, is_binary, old_path",
        ),
    )
    op.add_column(
        "work_items",
        sa.Column(
            "merge_commit_sha",
            sa.Text(),
            nullable=True,
            comment="SHA of the squash commit on main; enables lazy git diff for completed-not-archived items",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_items", "merge_commit_sha")
    op.drop_column("work_items", "diff_summary")
    op.drop_column("work_items", "diff_text")
    op.drop_column("step_runs", "diff_summary")
    op.drop_column("step_runs", "diff_text")
    # ### end Alembic commands ###
