"""CR-00056: add prompt_text and fix_prompt_text to step_runs

Revision ID: 21de61b41cec
Revises: 678ac4dd44b7
Create Date: 2026-05-16 23:28:04.865387

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "21de61b41cec"
down_revision: str | tuple[str, ...] | None = "678ac4dd44b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "step_runs",
        sa.Column(
            "prompt_text",
            sa.Text(),
            nullable=True,
            comment="Snapshot of the prompt content captured at step launch. Set by the daemon when this StepRun is created. NULL for pre-CR-00056 rows. Append-only — never updated after creation. (CR-00056)",
        ),
    )
    op.add_column(
        "step_runs",
        sa.Column(
            "fix_prompt_text",
            sa.Text(),
            nullable=True,
            comment="Snapshot of the fix-cycle prompt content for retry runs. Set by the daemon when a fix-cycle StepRun is created. NULL for non-fix-cycle runs and pre-CR-00056 rows. Append-only. (CR-00056)",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("step_runs", "fix_prompt_text")
    op.drop_column("step_runs", "prompt_text")
    # ### end Alembic commands ###
