"""add db_backup_jobs

Revision ID: 3448ea03937d
Revises: ea7f8a0d065f
Create Date: 2026-06-01 14:56:01.726187

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3448ea03937d"
down_revision: str | tuple[str, ...] | None = "c7d9disable47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "db_backup_jobs",
        sa.Column(
            "id",
            sa.Text(),
            server_default=sa.text("gen_random_uuid()::text"),
            nullable=False,
            comment="UUID as text, generated by PostgreSQL",
        ),
        sa.Column(
            "backup_type", sa.Enum("scheduled", "manual", name="db_backup_type"), nullable=False
        ),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "success", "failed", name="db_backup_status"),
            server_default=sa.text("'queued'"),
            nullable=False,
        ),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("bytes", sa.BigInteger(), nullable=True),
        sa.Column("alembic_revision", sa.Text(), nullable=True),
        sa.Column("instance_id", sa.Text(), nullable=True),
        sa.Column("row_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="Tracks orchestration database backup executions (scheduled and manual)",
    )
    op.create_index(
        "idx_db_backup_jobs_type_status_created",
        "db_backup_jobs",
        ["backup_type", "status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_db_backup_jobs_type_status_created", table_name="db_backup_jobs")
    op.drop_table("db_backup_jobs")
    op.execute("DROP TYPE IF EXISTS db_backup_status")
    op.execute("DROP TYPE IF EXISTS db_backup_type")
    # ### end Alembic commands ###
