"""F-00085 auto merge verdicts and project config

Revision ID: 678ac4dd44b7
Revises: d1e2f3gpt53c
Create Date: 2026-05-16 20:07:00.325178

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "678ac4dd44b7"
down_revision: str | tuple[str, ...] | None = "d1e2f3gpt53c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auto_merge_project_config",
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("phase", sa.Integer(), nullable=True),
        sa.Column("runtime_option_id", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "phase IS NULL OR phase IN (0, 1)", name="ck_auto_merge_project_config_phase"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["runtime_option_id"], ["agent_runtime_options.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("project_id"),
        comment="Per-project operator overrides for auto-merge behavior",
    )
    op.create_table(
        "merge_auto_verdicts",
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("daemon_event_id", sa.BigInteger(), nullable=False),
        sa.Column("verdict", sa.Text(), nullable=False),
        sa.Column("verdict_notes", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("verdicted_by", sa.Text(), nullable=True),
        sa.Column(
            "verdicted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "verdict IN ('pending','correct','wrong','partial')",
            name="ck_merge_auto_verdicts_verdict",
        ),
        sa.ForeignKeyConstraint(["daemon_event_id"], ["daemon_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "daemon_event_id"),
        comment="Operator verdicts for auto-merge outcomes per daemon event",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("merge_auto_verdicts")
    op.drop_table("auto_merge_project_config")
    # ### end Alembic commands ###
