"""Add id_allocations table for idempotent next-id

Revision ID: 7ef0b420c58f
Revises: a1b2c3fixmm
Create Date: 2026-05-14 22:59:23.691947

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "7ef0b420c58f"
down_revision: str | tuple[str, ...] | None = "a1b2c3fixmm"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "id_allocations",
        sa.Column(
            "prefix",
            sa.Text(),
            nullable=False,
            comment="ID prefix: 'F' (Feature), 'I' (Issue), 'CR' (ChangeRequest), 'BATCH'",
        ),
        sa.Column("number", sa.Integer(), nullable=False, comment="Allocated sequence number"),
        sa.Column(
            "idempotency_key",
            sa.Text(),
            nullable=True,
            comment="Client-supplied idempotency key (NULL when no key provided)",
        ),
        sa.Column(
            "project_id", sa.Text(), nullable=True, comment="Project that requested this allocation"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC timestamp of allocation",
        ),
        sa.PrimaryKeyConstraint("prefix", "number"),
        comment="Audit log of keyed ID allocations for idempotent iw next-id (CR-00053)",
    )
    op.create_index(
        "idx_id_allocations_key",
        "id_allocations",
        ["prefix", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_id_allocations_key",
        table_name="id_allocations",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_table("id_allocations")
    # ### end Alembic commands ###
