"""sync schema with model comments and indexes

Revision ID: 7f1a75bb5c2d
Revises: c35d5b257eab
Create Date: 2026-05-07 08:42:57.445499

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7f1a75bb5c2d"
down_revision: str | None = "c35d5b257eab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "batches",
        "plan_path",
        existing_type=sa.TEXT(),
        comment="Path to the batch execution plan document (legacy)",
        existing_comment="Path to the batch execution plan document",
        existing_nullable=True,
    )
    op.alter_column(
        "batches",
        "diagram_path",
        existing_type=sa.TEXT(),
        comment="Path to the diagram file (legacy)",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_conversations",
        "id",
        existing_type=sa.TEXT(),
        comment="UUID as text, generated by PostgreSQL",
        existing_nullable=False,
        existing_server_default=sa.text("(gen_random_uuid())::text"),
    )
    op.alter_column(
        "chat_conversations",
        "project_id",
        existing_type=sa.TEXT(),
        comment="FK to projects(id); app-layer enforcement of project scoping",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_conversations",
        "session_id",
        existing_type=sa.TEXT(),
        comment="Browser session cookie (iw_chat_session) — scoped to (project_id, session_id)",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_conversations",
        "module_path",
        existing_type=sa.TEXT(),
        comment="Snapshot of module_path from the first turn; NULL for architecture-level chats",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_conversations",
        "context_level",
        existing_type=sa.TEXT(),
        comment="architecture | module — snapshot from first turn",
        existing_nullable=False,
        existing_server_default=sa.text("'architecture'::text"),
    )
    op.alter_column(
        "chat_conversations",
        "title",
        existing_type=sa.TEXT(),
        comment="First user question, truncated to 80 chars; NULL until first message persists",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_conversations",
        "rolling_summary",
        existing_type=sa.TEXT(),
        comment="Compact prose summary produced by ChatSummarizationJob; prepended to LLM history",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_conversations",
        "summary_through_message_id",
        existing_type=sa.TEXT(),
        comment="FK to chat_messages.id — last message included in rolling_summary",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_conversations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the conversation row was created",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "chat_conversations",
        "last_active_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Updated on every new assistant message",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "chat_conversations",
        "archived_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Soft-delete timestamp; NULL means active",
        existing_nullable=True,
    )
    op.create_table_comment(
        "chat_conversations",
        "Chat conversation sessions scoped to (project_id, session_id)",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "chat_messages",
        "id",
        existing_type=sa.TEXT(),
        comment="UUID as text, generated by PostgreSQL",
        existing_nullable=False,
        existing_server_default=sa.text("(gen_random_uuid())::text"),
    )
    op.alter_column(
        "chat_messages",
        "conversation_id",
        existing_type=sa.TEXT(),
        comment="FK to chat_conversations.id",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_messages",
        "role",
        existing_type=sa.TEXT(),
        comment="chat_message_role ENUM: user | assistant | system",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_messages",
        "content",
        existing_type=sa.TEXT(),
        comment="Message text; no upper bound — caller validates size",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_messages",
        "token_count",
        existing_type=sa.INTEGER(),
        comment="Token count via tiktoken (or len(content)//4 heuristic); set at insert, never updated",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "chat_messages",
        "message_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="JSONB metadata. Key: metadata (DDL column name) — Python attr: message_metadata (SQLAlchemy reserves 'metadata' on DeclarativeBase). Append-only: direct UPDATE forbidden EXCEPT to set metadata.error=true within the same transaction as the INSERT (stream-disconnected case).",
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "chat_messages",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the message row was inserted",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_table_comment(
        "chat_messages", "Append-only chat message turns.", existing_comment=None, schema=None
    )
    op.alter_column(
        "chat_summarization_jobs",
        "id",
        existing_type=sa.TEXT(),
        comment="UUID as text, generated by PostgreSQL",
        existing_nullable=False,
        existing_server_default=sa.text("(gen_random_uuid())::text"),
    )
    op.alter_column(
        "chat_summarization_jobs",
        "conversation_id",
        existing_type=sa.TEXT(),
        comment="FK to chat_conversations.id",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_summarization_jobs",
        "status",
        existing_type=sa.TEXT(),
        comment="queued | running | completed | failed | cancelled",
        existing_nullable=False,
        existing_server_default=sa.text("'queued'::text"),
    )
    op.alter_column(
        "chat_summarization_jobs",
        "messages_summarized",
        existing_type=sa.INTEGER(),
        comment="Number of messages summarised into rolling_summary",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "chat_summarization_jobs",
        "summary_through_message_id",
        existing_type=sa.TEXT(),
        comment="FK to chat_messages.id — last message included in the summary",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_summarization_jobs",
        "error_message",
        existing_type=sa.TEXT(),
        comment="Error detail when status=failed",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_summarization_jobs",
        "triggered_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the job was enqueued (hard budget overflow detected)",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "chat_summarization_jobs",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the daemon picked up the job",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_summarization_jobs",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the job finished (success or failure)",
        existing_nullable=True,
    )
    op.create_table_comment(
        "chat_summarization_jobs",
        "Background summarisation jobs for ChatConversation rolling_summary",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "code_index_jobs",
        "id",
        existing_type=sa.TEXT(),
        comment="UUID as text, generated by PostgreSQL",
        existing_nullable=False,
        existing_server_default=sa.text("(gen_random_uuid())::text"),
    )
    op.alter_column(
        "code_index_jobs",
        "public_id",
        existing_type=sa.TEXT(),
        nullable=True,
        existing_comment="Human-readable ID (CM-00001, CM-00002, ...). Allocated via id_sequences['CM'].",
    )
    op.alter_column(
        "code_index_jobs",
        "project_id",
        existing_type=sa.TEXT(),
        comment="FK to projects(id)",
        existing_nullable=False,
    )
    op.alter_column(
        "code_index_jobs",
        "status",
        existing_type=sa.TEXT(),
        comment="queued|running|completed|failed|cancelled",
        existing_nullable=False,
        existing_server_default=sa.text("'queued'::text"),
    )
    op.alter_column(
        "code_index_jobs",
        "provider",
        existing_type=sa.TEXT(),
        comment="Index provider: local (only value in v1)",
        existing_nullable=False,
        existing_server_default=sa.text("'local'::text"),
    )
    op.alter_column(
        "code_index_jobs",
        "llm_model",
        existing_type=sa.TEXT(),
        comment="LLM model name; None = use tier default",
        existing_nullable=True,
    )
    op.alter_column(
        "code_index_jobs",
        "embed_model",
        existing_type=sa.TEXT(),
        comment="Embedding model name; None = use tier default",
        existing_nullable=True,
    )
    op.alter_column(
        "code_index_jobs",
        "index_tier",
        existing_type=sa.TEXT(),
        comment="fast|balanced|quality",
        existing_nullable=True,
    )
    op.alter_column(
        "code_index_jobs",
        "files_discovered",
        existing_type=sa.INTEGER(),
        comment="Total files found",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "code_index_jobs",
        "files_indexed",
        existing_type=sa.INTEGER(),
        comment="Files successfully indexed",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "code_index_jobs",
        "chunks_created",
        existing_type=sa.INTEGER(),
        comment="Total chunks produced",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "code_index_jobs",
        "languages_detected",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="List of detected language names",
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "code_index_jobs",
        "errors",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="List of error messages",
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "code_index_jobs",
        "doc_id",
        existing_type=sa.TEXT(),
        comment="FK to project_docs(id); nullable, SET NULL on delete",
        existing_nullable=True,
    )
    op.alter_column(
        "code_index_jobs",
        "triggered_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the job was triggered",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "code_index_jobs",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the job finished (success or failure)",
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_daemon_events_project"), table_name="daemon_events")
    op.create_index(
        "idx_daemon_events_project", "daemon_events", ["project_id", "created_at"], unique=False
    )
    op.drop_index(op.f("idx_daemon_events_recent"), table_name="daemon_events")
    op.create_index("idx_daemon_events_recent", "daemon_events", ["created_at"], unique=False)
    op.drop_index(op.f("idx_daemon_events_type"), table_name="daemon_events")
    op.create_index(
        "idx_daemon_events_type", "daemon_events", ["event_type", "created_at"], unique=False
    )
    op.alter_column(
        "doc_generation_jobs",
        "skill_used",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "doc_generation_jobs",
        "trigger_reason",
        existing_type=sa.TEXT(),
        comment="Why the job was created (e.g., 'batch-merge:B-00042:F-00013')",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_generation_jobs",
        "lint_warnings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="List of lint warning objects {rule, message, section}",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_generation_jobs",
        "report",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Structured post-mortem of the job: outcome, duration_seconds, skill_used, cli_tool, command_issued, log_size_bytes, log_line_count, tool_calls, doc_update_invocations, lint_warning_count, diagnosis.",
        existing_comment="Structured post-mortem of the doc-generation job: outcome, duration_seconds, skill_used, cli_tool, command_issued, log_size_bytes, log_line_count, tool_calls, doc_update_invocations, lint_warning_count, diagnosis.",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_generation_jobs",
        "section_guides_snapshot",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Section guides snapshotted at job creation: {section_name: guide_md, ...}.",
        existing_comment="Section guides snapshotted at job creation: {section_name: guide_md, ...}",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_index_jobs",
        "id",
        existing_type=sa.TEXT(),
        comment="UUID as text, generated by PostgreSQL",
        existing_nullable=False,
        existing_server_default=sa.text("(gen_random_uuid())::text"),
    )
    op.alter_column(
        "doc_index_jobs",
        "project_id",
        existing_type=sa.TEXT(),
        comment="FK to projects(id)",
        existing_nullable=False,
    )
    op.alter_column(
        "doc_index_jobs",
        "status",
        existing_type=sa.TEXT(),
        comment="queued|running|completed|failed|cancelled",
        existing_nullable=False,
        existing_server_default=sa.text("'queued'::text"),
    )
    op.alter_column(
        "doc_index_jobs",
        "provider",
        existing_type=sa.TEXT(),
        comment="Index provider: local (only value in v1)",
        existing_nullable=False,
        existing_server_default=sa.text("'local'::text"),
    )
    op.alter_column(
        "doc_index_jobs",
        "llm_model",
        existing_type=sa.TEXT(),
        comment="LLM model name; None = use tier default",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_index_jobs",
        "embed_model",
        existing_type=sa.TEXT(),
        comment="Embedding model name; None = use tier default",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_index_jobs",
        "index_tier",
        existing_type=sa.TEXT(),
        comment="fast|balanced|quality",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_index_jobs",
        "items_discovered",
        existing_type=sa.INTEGER(),
        comment="Total items found",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "doc_index_jobs",
        "items_indexed",
        existing_type=sa.INTEGER(),
        comment="Items successfully indexed",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "doc_index_jobs",
        "chunks_created",
        existing_type=sa.INTEGER(),
        comment="Total chunks produced",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "doc_index_jobs",
        "errors",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="List of error messages",
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "doc_index_jobs",
        "triggered_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the job was triggered",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "doc_index_jobs",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the job started",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_index_jobs",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the job finished (success or failure)",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_index_jobs",
        "error_message",
        existing_type=sa.TEXT(),
        comment="Error message if status='failed'",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_instance_guides",
        "doc_id",
        existing_type=sa.TEXT(),
        comment="FK to project_docs.id",
        existing_comment="Composite PK matching project_docs.id (format: project_id:doc_id).",
        existing_nullable=False,
    )
    op.alter_column(
        "doc_instance_guides",
        "guide_md",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Markdown editorial instructions specific to this document.",
        existing_nullable=False,
    )
    op.alter_column(
        "doc_instance_guides",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp of last guide edit.",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_table_comment(
        "doc_instance_guides",
        "Instance-level guide override for a specific ProjectDoc",
        existing_comment="Per-document editorial guide overrides — highest priority, overrides doc_type_guides.",
        schema=None,
    )
    op.alter_column(
        "doc_section_guides",
        "doc_id",
        existing_type=sa.TEXT(),
        comment="FK to project_docs.id (composite: project_id:doc_id).",
        existing_comment="FK to project_docs.id (composite: project_id:doc_id). ON DELETE CASCADE.",
        existing_nullable=False,
    )
    op.drop_index(op.f("uq_doc_section_guides_doc_section"), table_name="doc_section_guides")
    op.create_unique_constraint(
        "uq_doc_section_guides_doc_section", "doc_section_guides", ["doc_id", "section_name"]
    )
    op.alter_column(
        "doc_type_guides",
        "doc_type",
        existing_type=sa.TEXT(),
        comment="DocType value (e.g. 'api', 'module')",
        existing_comment="DocType enum value (e.g. marketing, module, api).",
        existing_nullable=False,
    )
    op.alter_column(
        "doc_type_guides",
        "guide_md",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Markdown editorial guidelines for this doc type.",
        existing_nullable=False,
    )
    op.alter_column(
        "doc_type_guides",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp of last guide edit.",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_table_comment(
        "doc_type_guides",
        "Editable editorial guideline per DocType",
        existing_comment="Per-doc-type editorial guidelines, editable from the UI.",
        schema=None,
    )
    op.create_table_comment(
        "keep_alive_config",
        "Singleton global config for the Keep-Alive Scheduler",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "keep_alive_runs",
        "slot_time",
        existing_type=sa.VARCHAR(length=5),
        comment="Snapshot of 'HH:MM' at fire time",
        existing_nullable=False,
    )
    op.alter_column(
        "keep_alive_runs",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment="success|failed|retried_success|retried_failed",
        existing_nullable=False,
    )
    op.create_table_comment(
        "keep_alive_runs",
        "Execution log for keep-alive firings",
        existing_comment=None,
        schema=None,
    )
    op.create_table_comment(
        "keep_alive_slots", "Scheduled keep-alive time slots", existing_comment=None, schema=None
    )
    op.alter_column(
        "oss_finding",
        "scan_id",
        existing_type=sa.BIGINT(),
        comment=None,
        existing_comment="FK to oss_scan.id",
        existing_nullable=False,
    )
    op.alter_column(
        "oss_finding",
        "domain",
        existing_type=sa.TEXT(),
        comment="license, secrets, etc.",
        existing_comment="Domain: license, secrets, etc.",
        existing_nullable=False,
    )
    op.alter_column(
        "oss_scan",
        "project_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="FK to projects.id",
        existing_nullable=False,
    )
    op.alter_column(
        "oss_scan",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When the scan started",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "oss_scan",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When the scan finished",
        existing_nullable=True,
    )
    op.alter_column(
        "oss_tool_run",
        "scan_id",
        existing_type=sa.BIGINT(),
        comment=None,
        existing_comment="FK to oss_scan.id",
        existing_nullable=False,
    )
    op.alter_column(
        "pending_migration_log",
        "old_revision",
        existing_type=sa.TEXT(),
        comment="Previous down_revision string before the rebase phase rewrote it (phase='rebase' only)",
        existing_comment="Previous down_revision before the rebase phase rewrote it",
        existing_nullable=True,
    )
    op.alter_column(
        "project_docs",
        "broken_links",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="List of {url, type, status} objects from link validation",
        existing_nullable=True,
    )
    op.alter_column(
        "project_oss_job",
        "project_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="FK to projects.id",
        existing_nullable=False,
    )
    op.alter_column(
        "project_oss_job",
        "base_sha",
        existing_type=sa.TEXT(),
        comment="Git HEAD SHA when the job was fired",
        existing_comment="Git HEAD SHA when Prepare was fired",
        existing_nullable=True,
    )
    op.create_table_comment(
        "project_oss_job",
        "Async OSS scan/install/fix job tracking",
        existing_comment="Async OSS scan/prepare/publish/install job tracking",
        schema=None,
    )
    op.alter_column(
        "step_runs",
        "log_content",
        existing_type=sa.TEXT(),
        comment="Captured log content (ANSI-stripped, truncated) for fast DB access",
        existing_comment="Agent stdout/stderr captured on completion",
        existing_nullable=True,
    )
    op.alter_column(
        "work_items",
        "impacted_paths",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Globs declaring files this work item is expected to touch. Source of truth for the cross-batch launch-time conflict gate (F-00076) and the workflow-manifest.json:scope.allowed_paths merge gate. Populated by orch/cli/item_commands.py:register() from the design doc's 'Impacted Paths' section, with a regex fallback over design_doc_content when the section is absent.",
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.drop_index(op.f("idx_work_items_created"), table_name="work_items")
    op.create_index(
        "idx_work_items_created", "work_items", ["project_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_work_items_created", table_name="work_items")
    op.create_index(
        op.f("idx_work_items_created"),
        "work_items",
        ["project_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "work_items",
        "impacted_paths",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="Globs declaring files this work item is expected to touch. Source of truth for the cross-batch launch-time conflict gate (F-00076) and the workflow-manifest.json:scope.allowed_paths merge gate. Populated by orch/cli/item_commands.py:register() from the design doc's 'Impacted Paths' section, with a regex fallback over design_doc_content when the section is absent.",
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "step_runs",
        "log_content",
        existing_type=sa.TEXT(),
        comment="Agent stdout/stderr captured on completion",
        existing_comment="Captured log content (ANSI-stripped, truncated) for fast DB access",
        existing_nullable=True,
    )
    op.create_table_comment(
        "project_oss_job",
        "Async OSS scan/prepare/publish/install job tracking",
        existing_comment="Async OSS scan/install/fix job tracking",
        schema=None,
    )
    op.alter_column(
        "project_oss_job",
        "base_sha",
        existing_type=sa.TEXT(),
        comment="Git HEAD SHA when Prepare was fired",
        existing_comment="Git HEAD SHA when the job was fired",
        existing_nullable=True,
    )
    op.alter_column(
        "project_oss_job",
        "project_id",
        existing_type=sa.TEXT(),
        comment="FK to projects.id",
        existing_nullable=False,
    )
    op.alter_column(
        "project_docs",
        "broken_links",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="List of {url, type, status} objects from link validation",
        existing_nullable=True,
    )
    op.alter_column(
        "pending_migration_log",
        "old_revision",
        existing_type=sa.TEXT(),
        comment="Previous down_revision before the rebase phase rewrote it",
        existing_comment="Previous down_revision string before the rebase phase rewrote it (phase='rebase' only)",
        existing_nullable=True,
    )
    op.alter_column(
        "oss_tool_run",
        "scan_id",
        existing_type=sa.BIGINT(),
        comment="FK to oss_scan.id",
        existing_nullable=False,
    )
    op.alter_column(
        "oss_scan",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the scan finished",
        existing_nullable=True,
    )
    op.alter_column(
        "oss_scan",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the scan started",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "oss_scan",
        "project_id",
        existing_type=sa.TEXT(),
        comment="FK to projects.id",
        existing_nullable=False,
    )
    op.alter_column(
        "oss_finding",
        "domain",
        existing_type=sa.TEXT(),
        comment="Domain: license, secrets, etc.",
        existing_comment="license, secrets, etc.",
        existing_nullable=False,
    )
    op.alter_column(
        "oss_finding",
        "scan_id",
        existing_type=sa.BIGINT(),
        comment="FK to oss_scan.id",
        existing_nullable=False,
    )
    op.drop_table_comment(
        "keep_alive_slots", existing_comment="Scheduled keep-alive time slots", schema=None
    )
    op.drop_table_comment(
        "keep_alive_runs", existing_comment="Execution log for keep-alive firings", schema=None
    )
    op.alter_column(
        "keep_alive_runs",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="success|failed|retried_success|retried_failed",
        existing_nullable=False,
    )
    op.alter_column(
        "keep_alive_runs",
        "slot_time",
        existing_type=sa.VARCHAR(length=5),
        comment=None,
        existing_comment="Snapshot of 'HH:MM' at fire time",
        existing_nullable=False,
    )
    op.drop_table_comment(
        "keep_alive_config",
        existing_comment="Singleton global config for the Keep-Alive Scheduler",
        schema=None,
    )
    op.create_table_comment(
        "doc_type_guides",
        "Per-doc-type editorial guidelines, editable from the UI.",
        existing_comment="Editable editorial guideline per DocType",
        schema=None,
    )
    op.alter_column(
        "doc_type_guides",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp of last guide edit.",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "doc_type_guides",
        "guide_md",
        existing_type=sa.TEXT(),
        comment="Markdown editorial guidelines for this doc type.",
        existing_nullable=False,
    )
    op.alter_column(
        "doc_type_guides",
        "doc_type",
        existing_type=sa.TEXT(),
        comment="DocType enum value (e.g. marketing, module, api).",
        existing_comment="DocType value (e.g. 'api', 'module')",
        existing_nullable=False,
    )
    op.drop_constraint("uq_doc_section_guides_doc_section", "doc_section_guides", type_="unique")
    op.create_index(
        op.f("uq_doc_section_guides_doc_section"),
        "doc_section_guides",
        ["doc_id", "section_name"],
        unique=True,
    )
    op.alter_column(
        "doc_section_guides",
        "doc_id",
        existing_type=sa.TEXT(),
        comment="FK to project_docs.id (composite: project_id:doc_id). ON DELETE CASCADE.",
        existing_comment="FK to project_docs.id (composite: project_id:doc_id).",
        existing_nullable=False,
    )
    op.create_table_comment(
        "doc_instance_guides",
        "Per-document editorial guide overrides — highest priority, overrides doc_type_guides.",
        existing_comment="Instance-level guide override for a specific ProjectDoc",
        schema=None,
    )
    op.alter_column(
        "doc_instance_guides",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp of last guide edit.",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "doc_instance_guides",
        "guide_md",
        existing_type=sa.TEXT(),
        comment="Markdown editorial instructions specific to this document.",
        existing_nullable=False,
    )
    op.alter_column(
        "doc_instance_guides",
        "doc_id",
        existing_type=sa.TEXT(),
        comment="Composite PK matching project_docs.id (format: project_id:doc_id).",
        existing_comment="FK to project_docs.id",
        existing_nullable=False,
    )
    op.alter_column(
        "doc_index_jobs",
        "error_message",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Error message if status='failed'",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_index_jobs",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When the job finished (success or failure)",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_index_jobs",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When the job started",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_index_jobs",
        "triggered_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When the job was triggered",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "doc_index_jobs",
        "errors",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="List of error messages",
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "doc_index_jobs",
        "chunks_created",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Total chunks produced",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "doc_index_jobs",
        "items_indexed",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Items successfully indexed",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "doc_index_jobs",
        "items_discovered",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Total items found",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "doc_index_jobs",
        "index_tier",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="fast|balanced|quality",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_index_jobs",
        "embed_model",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Embedding model name; None = use tier default",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_index_jobs",
        "llm_model",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="LLM model name; None = use tier default",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_index_jobs",
        "provider",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Index provider: local (only value in v1)",
        existing_nullable=False,
        existing_server_default=sa.text("'local'::text"),
    )
    op.alter_column(
        "doc_index_jobs",
        "status",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="queued|running|completed|failed|cancelled",
        existing_nullable=False,
        existing_server_default=sa.text("'queued'::text"),
    )
    op.alter_column(
        "doc_index_jobs",
        "project_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="FK to projects(id)",
        existing_nullable=False,
    )
    op.alter_column(
        "doc_index_jobs",
        "id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="UUID as text, generated by PostgreSQL",
        existing_nullable=False,
        existing_server_default=sa.text("(gen_random_uuid())::text"),
    )
    op.alter_column(
        "doc_generation_jobs",
        "section_guides_snapshot",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Section guides snapshotted at job creation: {section_name: guide_md, ...}",
        existing_comment="Section guides snapshotted at job creation: {section_name: guide_md, ...}.",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_generation_jobs",
        "report",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Structured post-mortem of the doc-generation job: outcome, duration_seconds, skill_used, cli_tool, command_issued, log_size_bytes, log_line_count, tool_calls, doc_update_invocations, lint_warning_count, diagnosis.",
        existing_comment="Structured post-mortem of the job: outcome, duration_seconds, skill_used, cli_tool, command_issued, log_size_bytes, log_line_count, tool_calls, doc_update_invocations, lint_warning_count, diagnosis.",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_generation_jobs",
        "lint_warnings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="List of lint warning objects {rule, message, section}",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_generation_jobs",
        "trigger_reason",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Why the job was created (e.g., 'batch-merge:B-00042:F-00013')",
        existing_nullable=True,
    )
    op.alter_column(
        "doc_generation_jobs",
        "skill_used",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.drop_index("idx_daemon_events_type", table_name="daemon_events")
    op.create_index(
        op.f("idx_daemon_events_type"),
        "daemon_events",
        ["event_type", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index("idx_daemon_events_recent", table_name="daemon_events")
    op.create_index(
        op.f("idx_daemon_events_recent"),
        "daemon_events",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.drop_index("idx_daemon_events_project", table_name="daemon_events")
    op.create_index(
        op.f("idx_daemon_events_project"),
        "daemon_events",
        ["project_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "code_index_jobs",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When the job finished (success or failure)",
        existing_nullable=True,
    )
    op.alter_column(
        "code_index_jobs",
        "triggered_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When the job was triggered",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "code_index_jobs",
        "doc_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="FK to project_docs(id); nullable, SET NULL on delete",
        existing_nullable=True,
    )
    op.alter_column(
        "code_index_jobs",
        "errors",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="List of error messages",
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "code_index_jobs",
        "languages_detected",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="List of detected language names",
        existing_nullable=False,
        existing_server_default=sa.text("'[]'::jsonb"),
    )
    op.alter_column(
        "code_index_jobs",
        "chunks_created",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Total chunks produced",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "code_index_jobs",
        "files_indexed",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Files successfully indexed",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "code_index_jobs",
        "files_discovered",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Total files found",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "code_index_jobs",
        "index_tier",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="fast|balanced|quality",
        existing_nullable=True,
    )
    op.alter_column(
        "code_index_jobs",
        "embed_model",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Embedding model name; None = use tier default",
        existing_nullable=True,
    )
    op.alter_column(
        "code_index_jobs",
        "llm_model",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="LLM model name; None = use tier default",
        existing_nullable=True,
    )
    op.alter_column(
        "code_index_jobs",
        "provider",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Index provider: local (only value in v1)",
        existing_nullable=False,
        existing_server_default=sa.text("'local'::text"),
    )
    op.alter_column(
        "code_index_jobs",
        "status",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="queued|running|completed|failed|cancelled",
        existing_nullable=False,
        existing_server_default=sa.text("'queued'::text"),
    )
    op.alter_column(
        "code_index_jobs",
        "project_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="FK to projects(id)",
        existing_nullable=False,
    )
    op.alter_column(
        "code_index_jobs",
        "public_id",
        existing_type=sa.TEXT(),
        nullable=False,
        existing_comment="Human-readable ID (CM-00001, CM-00002, ...). Allocated via id_sequences['CM'].",
    )
    op.alter_column(
        "code_index_jobs",
        "id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="UUID as text, generated by PostgreSQL",
        existing_nullable=False,
        existing_server_default=sa.text("(gen_random_uuid())::text"),
    )
    op.drop_table_comment(
        "chat_summarization_jobs",
        existing_comment="Background summarisation jobs for ChatConversation rolling_summary",
        schema=None,
    )
    op.alter_column(
        "chat_summarization_jobs",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When the job finished (success or failure)",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_summarization_jobs",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When the daemon picked up the job",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_summarization_jobs",
        "triggered_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When the job was enqueued (hard budget overflow detected)",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "chat_summarization_jobs",
        "error_message",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Error detail when status=failed",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_summarization_jobs",
        "summary_through_message_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="FK to chat_messages.id — last message included in the summary",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_summarization_jobs",
        "messages_summarized",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Number of messages summarised into rolling_summary",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "chat_summarization_jobs",
        "status",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="queued | running | completed | failed | cancelled",
        existing_nullable=False,
        existing_server_default=sa.text("'queued'::text"),
    )
    op.alter_column(
        "chat_summarization_jobs",
        "conversation_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="FK to chat_conversations.id",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_summarization_jobs",
        "id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="UUID as text, generated by PostgreSQL",
        existing_nullable=False,
        existing_server_default=sa.text("(gen_random_uuid())::text"),
    )
    op.drop_table_comment(
        "chat_messages", existing_comment="Append-only chat message turns.", schema=None
    )
    op.alter_column(
        "chat_messages",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When the message row was inserted",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "chat_messages",
        "message_metadata",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=None,
        existing_comment="JSONB metadata. Key: metadata (DDL column name) — Python attr: message_metadata (SQLAlchemy reserves 'metadata' on DeclarativeBase). Append-only: direct UPDATE forbidden EXCEPT to set metadata.error=true within the same transaction as the INSERT (stream-disconnected case).",
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "chat_messages",
        "token_count",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Token count via tiktoken (or len(content)//4 heuristic); set at insert, never updated",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "chat_messages",
        "content",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Message text; no upper bound — caller validates size",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_messages",
        "role",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="chat_message_role ENUM: user | assistant | system",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_messages",
        "conversation_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="FK to chat_conversations.id",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_messages",
        "id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="UUID as text, generated by PostgreSQL",
        existing_nullable=False,
        existing_server_default=sa.text("(gen_random_uuid())::text"),
    )
    op.drop_table_comment(
        "chat_conversations",
        existing_comment="Chat conversation sessions scoped to (project_id, session_id)",
        schema=None,
    )
    op.alter_column(
        "chat_conversations",
        "archived_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Soft-delete timestamp; NULL means active",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_conversations",
        "last_active_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Updated on every new assistant message",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "chat_conversations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="When the conversation row was created",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "chat_conversations",
        "summary_through_message_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="FK to chat_messages.id — last message included in rolling_summary",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_conversations",
        "rolling_summary",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Compact prose summary produced by ChatSummarizationJob; prepended to LLM history",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_conversations",
        "title",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="First user question, truncated to 80 chars; NULL until first message persists",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_conversations",
        "context_level",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="architecture | module — snapshot from first turn",
        existing_nullable=False,
        existing_server_default=sa.text("'architecture'::text"),
    )
    op.alter_column(
        "chat_conversations",
        "module_path",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Snapshot of module_path from the first turn; NULL for architecture-level chats",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_conversations",
        "session_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Browser session cookie (iw_chat_session) — scoped to (project_id, session_id)",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_conversations",
        "project_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="FK to projects(id); app-layer enforcement of project scoping",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_conversations",
        "id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="UUID as text, generated by PostgreSQL",
        existing_nullable=False,
        existing_server_default=sa.text("(gen_random_uuid())::text"),
    )
    op.alter_column(
        "batches",
        "diagram_path",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Path to the diagram file (legacy)",
        existing_nullable=True,
    )
    op.alter_column(
        "batches",
        "plan_path",
        existing_type=sa.TEXT(),
        comment="Path to the batch execution plan document",
        existing_comment="Path to the batch execution plan document (legacy)",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
