"""add_chat_tabs_column_comments

Revision ID: a3f1c9e2b7d4
Revises: 76250ecb2593
Create Date: 2026-05-28 00:00:00.000000

Adds PostgreSQL column comments to the ``chat_tabs`` table for columns that
were defined with comments in the ORM model (``orch/db/models.py``) but whose
comments were not included in the original ``e45b45f74ea0_f_00086_chat_tabs``
migration.  Fixes the ``alembic check`` drift detected in CI.

Affected columns: ``title``, ``model``, ``project_id``,
``opencode_session_id``, ``closed_at``.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3f1c9e2b7d4"
down_revision: str | None = "76250ecb2593"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_tabs",
        "title",
        existing_type=sa.TEXT(),
        comment="Tab title shown in the strip; user-editable",
        existing_comment=None,
        existing_nullable=False,
        existing_server_default=sa.text("'New chat'"),
    )
    op.alter_column(
        "chat_tabs",
        "model",
        existing_type=sa.TEXT(),
        comment="Model identifier scoped to runtime (e.g., 'anthropic/claude-sonnet-4-7')",
        existing_comment=None,
        existing_nullable=False,
    )
    op.alter_column(
        "chat_tabs",
        "project_id",
        existing_type=sa.TEXT(),
        comment="FK to projects.id; deleting a project cascades to its tabs",
        existing_comment=None,
        existing_nullable=False,
    )
    op.alter_column(
        "chat_tabs",
        "opencode_session_id",
        existing_type=sa.TEXT(),
        comment="OpenCode session id; populated after first session create",
        existing_comment=None,
        existing_nullable=True,
    )
    op.alter_column(
        "chat_tabs",
        "closed_at",
        existing_type=sa.DateTime(timezone=True),
        comment="When the tab was soft-deleted; NULL when active",
        existing_comment=None,
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_tabs",
        "closed_at",
        existing_type=sa.DateTime(timezone=True),
        comment=None,
        existing_comment="When the tab was soft-deleted; NULL when active",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_tabs",
        "opencode_session_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="OpenCode session id; populated after first session create",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_tabs",
        "project_id",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="FK to projects.id; deleting a project cascades to its tabs",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_tabs",
        "model",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Model identifier scoped to runtime (e.g., 'anthropic/claude-sonnet-4-7')",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_tabs",
        "title",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Tab title shown in the strip; user-editable",
        existing_nullable=False,
        existing_server_default=sa.text("'New chat'"),
    )
    # ### end Alembic commands ###
