"""add mcp audit approval policy tables

Revision ID: b8ed7bbaa073
Revises: e2272b410220
Create Date: 2026-07-03 11:35:55.124619

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op  # noqa: F401
import sqlalchemy as sa  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b8ed7bbaa073"
down_revision: str | tuple[str, ...] | None = "e2272b410220"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_approval_requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("project_id", sa.Text(), nullable=True),
        sa.Column("tool_name", sa.Text(), nullable=False),
        sa.Column(
            "arguments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "denied",
                "consumed",
                "expired",
                name="mcp_approval_status",
                native_enum=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
        comment="Pending human-approval requests for gated MCP tools (R-00165).",
    )
    op.create_index(
        "idx_mcp_approval_status", "mcp_approval_requests", ["status", "created_at"], unique=False
    )
    op.create_table(
        "mcp_audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("project_id", sa.Text(), nullable=True),
        sa.Column("tool_name", sa.Text(), nullable=False),
        sa.Column("actor", sa.Text(), nullable=True),
        sa.Column(
            "arguments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("decision", sa.Text(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="Append-only audit trail of MCP tool invocations (R-00165).",
    )
    op.create_index(
        "idx_mcp_audit_project", "mcp_audit_log", ["project_id", "created_at"], unique=False
    )
    op.create_index(
        "idx_mcp_audit_tool", "mcp_audit_log", ["tool_name", "created_at"], unique=False
    )
    op.create_table(
        "mcp_policies",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Text(), nullable=False),
        sa.Column("tool_name", sa.Text(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("allow", "ask", "deny", name="mcp_policy_decision", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "tool_name", name="uq_mcp_policy_project_tool"),
        comment="Per-project per-tool runtime policy overrides for MCP tools (R-00165).",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mcp_policies")
    op.drop_index("idx_mcp_audit_tool", table_name="mcp_audit_log")
    op.drop_index("idx_mcp_audit_project", table_name="mcp_audit_log")
    op.drop_table("mcp_audit_log")
    op.drop_index("idx_mcp_approval_status", table_name="mcp_approval_requests")
    op.drop_table("mcp_approval_requests")
    # ### end Alembic commands ###
