"""F-00081 agent runtime options

Revision ID: ff23f562353b
Revises: 7fcf3ddaa283
Create Date: 2026-05-08 21:47:42.547609

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff23f562353b"
down_revision: str | None = "1713bc13a11d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runtime_options",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cli_tool", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("cli_label", sa.Text(), nullable=False),
        sa.Column("model_label", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "NOT (is_default = true AND enabled = false)",
            name="ck_agent_runtime_options_default_must_be_enabled",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cli_tool", "model", name="uq_agent_runtime_options_cli_model"),
        comment="Catalogue of curated (cli_tool, model) pairs the daemon can launch.",
    )
    op.create_index(
        "uq_agent_runtime_options_one_default",
        "agent_runtime_options",
        ["is_default"],
        unique=True,
        postgresql_where=sa.text("is_default = true"),
    )
    # Seed rows: 5 curated (cli_tool, model) pairs (F-00081)
    op.bulk_insert(
        sa.table(
            "agent_runtime_options",
            sa.Column("id", sa.Integer()),
            sa.Column("cli_tool", sa.Text()),
            sa.Column("model", sa.Text()),
            sa.Column("cli_label", sa.Text()),
            sa.Column("model_label", sa.Text()),
            sa.Column("display_name", sa.Text()),
            sa.Column("is_default", sa.Boolean()),
            sa.Column("enabled", sa.Boolean()),
            sa.Column("sort_order", sa.Integer()),
        ),
        [
            {
                "id": 1,
                "cli_tool": "opencode",
                "model": "minimax",
                "cli_label": "OpenCode",
                "model_label": "MiniMax 2.7",
                "display_name": "OpenCode + MiniMax 2.7",
                "is_default": True,
                "enabled": True,
                "sort_order": 10,
            },
            {
                "id": 2,
                "cli_tool": "opencode",
                "model": "claude-sonnet-4-6",
                "cli_label": "OpenCode",
                "model_label": "Claude Sonnet 4.6",
                "display_name": "OpenCode + Claude Sonnet 4.6",
                "is_default": False,
                "enabled": True,
                "sort_order": 20,
            },
            {
                "id": 3,
                "cli_tool": "opencode",
                "model": "claude-opus-4-7",
                "cli_label": "OpenCode",
                "model_label": "Claude Opus 4.7",
                "display_name": "OpenCode + Claude Opus 4.7",
                "is_default": False,
                "enabled": True,
                "sort_order": 30,
            },
            {
                "id": 4,
                "cli_tool": "claude",
                "model": "claude-sonnet-4-6",
                "cli_label": "Claude Code",
                "model_label": "Sonnet 4.6",
                "display_name": "Claude Code + Sonnet 4.6",
                "is_default": False,
                "enabled": True,
                "sort_order": 40,
            },
            {
                "id": 5,
                "cli_tool": "claude",
                "model": "claude-opus-4-7",
                "cli_label": "Claude Code",
                "model_label": "Opus 4.7",
                "display_name": "Claude Code + Opus 4.7",
                "is_default": False,
                "enabled": True,
                "sort_order": 50,
            },
        ],
    )
    op.add_column(
        "step_runs",
        sa.Column(
            "agent_runtime_option_id",
            sa.Integer(),
            nullable=True,
            comment="The resolved (cli_tool, model) pair used for this run. F-00081.",
        ),
    )
    op.create_foreign_key(
        "fk_step_runs_agent_runtime_option_id",
        "step_runs",
        "agent_runtime_options",
        ["agent_runtime_option_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "work_items",
        sa.Column(
            "agent_runtime_option_id",
            sa.Integer(),
            nullable=True,
            comment="Override pair to use for this item; NULL = inherit. F-00081.",
        ),
    )
    op.alter_column(
        "work_items",
        "merge_commit_sha",
        existing_type=sa.TEXT(),
        comment="SHA of the squash commit on main; enables lazy git diff for completed items",
        existing_comment="SHA of the squash commit on main; enables lazy git diff for completed-not-archived items",
        existing_nullable=True,
    )
    op.create_foreign_key(
        "fk_work_items_agent_runtime_option_id",
        "work_items",
        "agent_runtime_options",
        ["agent_runtime_option_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.add_column(
        "workflow_steps",
        sa.Column(
            "agent_runtime_option_id",
            sa.Integer(),
            nullable=True,
            comment="Override pair to use for this step; NULL = inherit. F-00081.",
        ),
    )
    op.create_foreign_key(
        "fk_workflow_steps_agent_runtime_option_id",
        "workflow_steps",
        "agent_runtime_options",
        ["agent_runtime_option_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_workflow_steps_agent_runtime_option_id", "workflow_steps", type_="foreignkey"
    )
    op.drop_column("workflow_steps", "agent_runtime_option_id")
    op.drop_constraint("fk_work_items_agent_runtime_option_id", "work_items", type_="foreignkey")
    op.alter_column(
        "work_items",
        "merge_commit_sha",
        existing_type=sa.TEXT(),
        comment="SHA of the squash commit on main; enables lazy git diff for completed-not-archived items",
        existing_comment="SHA of the squash commit on main; enables lazy git diff for completed items",
        existing_nullable=True,
    )
    op.drop_column("work_items", "agent_runtime_option_id")
    op.drop_constraint("fk_step_runs_agent_runtime_option_id", "step_runs", type_="foreignkey")
    op.drop_column("step_runs", "agent_runtime_option_id")
    op.drop_index(
        "uq_agent_runtime_options_one_default",
        table_name="agent_runtime_options",
        postgresql_where=sa.text("is_default = true"),
    )
    op.drop_table("agent_runtime_options")
    # ### end Alembic commands ###
