"""Publish mode — emit scripts and checklist for flipping a repo to public.

Every destructive action is written to a shell script the USER runs
manually. Nothing in this module executes git-history-rewrite or
gh-repo-edit commands against live state.
"""

from __future__ import annotations

import stat
from pathlib import Path

from .context import Context
from .types import Finding

# ---------------------------------------------------------------------------
# Derive org/repo from remote URL
# ---------------------------------------------------------------------------


def parse_github_remote(remote_url: str) -> tuple[str, str] | None:
    """Extract (org, repo) from a GitHub SSH or HTTPS URL, or None."""
    if not remote_url:
        return None
    s = remote_url.strip().removesuffix(".git")
    # git@github.com:org/repo
    if s.startswith("git@github.com:"):
        s = s[len("git@github.com:") :]
    # https://github.com/org/repo
    elif "github.com/" in s:
        s = s.split("github.com/", 1)[1]
    else:
        return None
    parts = s.split("/")
    if len(parts) != 2:
        return None
    return parts[0], parts[1]


# ---------------------------------------------------------------------------
# History-rewrite emitters
# ---------------------------------------------------------------------------


def write_nuke_script(ctx: Context, history_secrets: int, history_pii: int) -> Path:
    """Write history-rewrite-nuke.sh — re-init with a single squashed commit.

    See references/history_rewrite.md for the full decision tree.
    """
    path = ctx.iw_dir / "history-rewrite-nuke.sh"
    content = f"""#!/usr/bin/env bash
# Generated by iw-oss-publish — NUKE-AND-REINIT history rewrite.
#
# ⚠  IRREVERSIBLE. Run ONLY if:
#   - You do NOT need to preserve git history, AND
#   - All collaborators are informed and will re-clone after the rewrite, AND
#   - No PRs depend on current commit SHAs.
#
# Replaces the entire history with a single "Initial public release" commit.
# Force-pushes to origin. Tags and branches other than main are deleted remotely.

set -euo pipefail

# ---------------------------------------------------------------------------
# Sanity preamble — DO NOT remove
# ---------------------------------------------------------------------------
if [ "$(git rev-parse --abbrev-ref HEAD 2>/dev/null)" = "" ]; then
  echo "error: not in a git repository" >&2; exit 1
fi
read -p "Nuke ALL history for $(git remote get-url origin 2>/dev/null || echo '<no remote>')? [type 'yes' to confirm] " CONFIRM
[ "$CONFIRM" = "yes" ] || {{ echo "aborted"; exit 0; }}

# ---------------------------------------------------------------------------
# 1. Snapshot the pre-nuke state for private archival (bundle format)
# ---------------------------------------------------------------------------
ARCHIVE="$HOME/iw-oss-publish-archives"
mkdir -p "$ARCHIVE"
BUNDLE="$ARCHIVE/{ctx.config.get("project_name", "repo")}-pre-public-$(date +%Y%m%d-%H%M%S).bundle"
git bundle create "$BUNDLE" --all
echo "  ✓ pre-nuke archive: $BUNDLE"

# ---------------------------------------------------------------------------
# 2. Create orphan root with the current working tree
# ---------------------------------------------------------------------------
git checkout --orphan iw-public-root
git add -A
git -c commit.gpgsign=false commit -s -m "Initial public release"
git branch -M main

# ---------------------------------------------------------------------------
# 3. Delete all other local branches and tags
# ---------------------------------------------------------------------------
for br in $(git branch --format='%(refname:short)' | grep -v '^main$' || true); do
  git branch -D "$br" || true
done
for tag in $(git tag -l); do
  git tag -d "$tag" || true
done

# ---------------------------------------------------------------------------
# 4. Force-push to origin (if remote exists)
# ---------------------------------------------------------------------------
if git remote get-url origin >/dev/null 2>&1; then
  read -p "Force-push main to origin (overwrites remote history)? [type 'push' to confirm] " GO
  if [ "$GO" = "push" ]; then
    git push --force origin main
    # Delete all remote branches except main
    for br in $(git ls-remote --heads origin | awk '{{print $2}}' | sed 's#refs/heads/##' | grep -v '^main$' || true); do
      git push --delete origin "$br" || true
    done
    # Delete all remote tags
    for tag in $(git ls-remote --tags origin | awk '{{print $2}}' | sed 's#refs/tags/##' | grep -v '^.*\\^{{}}$' || true); do
      git push --delete origin "$tag" || true
    done
    echo "  ✓ origin rewritten"
  else
    echo "  · skipped remote push; run manually when ready:"
    echo "    git push --force origin main"
  fi
fi

echo ""
echo "NUKE-AND-REINIT complete."
echo ""
echo "Follow-ups:"
echo "  1. All collaborators MUST re-clone (existing clones will diverge)."
{"  2. Open a GitHub Support ticket to purge cached commit SHAs:" if history_secrets else "#  2. (skipped — no secrets found in history)"}
{"     https://support.github.com/contact — 'Sensitive data in a repository'" if history_secrets else ""}
"""
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return path


def write_filter_repo_script(ctx: Context) -> Path:
    """Write history-rewrite-filter-repo.sh — surgical rewrite.

    This is a TEMPLATE script — the user must add specific paths / replacements
    based on their scan findings before running.
    """
    path = ctx.iw_dir / "history-rewrite-filter-repo.sh"
    content = """#!/usr/bin/env bash
# Generated by iw-oss-publish — FILTER-REPO surgical history rewrite.
#
# ⚠  IRREVERSIBLE. Force-pushes to origin.
# ⚠  This is a TEMPLATE. Fill in the PATHS_TO_PURGE and REPLACEMENTS arrays
#    below before running.
#
# See references/history_rewrite.md for the full command reference and pitfalls.

set -euo pipefail

# ---------------------------------------------------------------------------
# PATHS_TO_PURGE — files to remove from all history
# ---------------------------------------------------------------------------
PATHS_TO_PURGE=(
  # Examples — replace with paths from your scan findings:
  # "config/.env.production"
  # "secrets/"
  # "vendor/internal-licensed/"
)

# ---------------------------------------------------------------------------
# Literal-string replacements written to a file for git filter-repo
# Format: <literal>==><replacement>   (one per line)
# ---------------------------------------------------------------------------
REPLACEMENTS_FILE="$(mktemp)"
cat > "$REPLACEMENTS_FILE" <<'EOF_REPLACE'
# Example:
# old_api_key==>REDACTED
# https://internal.wiki/==>https://example.com/docs/
EOF_REPLACE

# ---------------------------------------------------------------------------
# Mailmap — pseudonymize historical author emails
# Format: <new-name> <new-email> <old-email>  (one per line)
# ---------------------------------------------------------------------------
MAILMAP_FILE="$(mktemp)"
cat > "$MAILMAP_FILE" <<'EOF_MAILMAP'
# Example (replaces a personal email with a GitHub noreply):
# <12345+sergiog@users.noreply.github.com> <sergio@personal.com>
EOF_MAILMAP

# ---------------------------------------------------------------------------
# Execution — REQUIRES A FRESH CLONE
# ---------------------------------------------------------------------------
if ! git-filter-repo --help >/dev/null 2>&1; then
  echo "error: git-filter-repo not installed. See install_tools.sh." >&2
  exit 1
fi

read -p "Run git-filter-repo with the configuration above? [type 'yes' to confirm] " CONFIRM
[ "$CONFIRM" = "yes" ] || { echo "aborted"; exit 0; }

# Path purge
if [ ${#PATHS_TO_PURGE[@]} -gt 0 ]; then
  git-filter-repo --force \\
    $(for p in "${PATHS_TO_PURGE[@]}"; do echo --path "$p"; done) \\
    --invert-paths
fi

# Content replace
if [ -s "$REPLACEMENTS_FILE" ] && grep -v '^#' "$REPLACEMENTS_FILE" | grep -q .; then
  git-filter-repo --force --replace-text "$REPLACEMENTS_FILE"
fi

# Author rewrite
if [ -s "$MAILMAP_FILE" ] && grep -v '^#' "$MAILMAP_FILE" | grep -q .; then
  git-filter-repo --force --mailmap "$MAILMAP_FILE"
fi

echo ""
echo "FILTER-REPO complete. Inspect the rewrite with:"
echo "  git log --oneline"
echo ""
echo "When satisfied, push (force-with-lease is SAFER than --force here):"
echo "  git remote add origin <url>  # filter-repo strips remotes for safety"
echo "  git push --force origin --all"
echo "  git push --force origin --tags"
"""
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return path


# ---------------------------------------------------------------------------
# gh playbook
# ---------------------------------------------------------------------------


def write_gh_playbook(ctx: Context, has_history_rewrite: bool) -> Path:
    """Write publish-playbook.sh — gh commands for flipping public + hardening."""
    path = ctx.iw_dir / "publish-playbook.sh"
    cfg = ctx.config
    parsed = parse_github_remote(ctx.repo.remote_url)
    if parsed:
        org, repo = parsed
    else:
        org = cfg.get("company_github_org", "innovation-ways")
        repo = cfg.get("project_name", ctx.target.name)

    desc = (
        cfg.get("project_description", "").strip()
        or f"{cfg.get('project_name', '')} — {cfg.get('company_brand', '')}"
    )
    homepage = cfg.get("homepage", "https://innovation-ways.com")

    topics: list[str] = sorted(ctx.ecosystems)
    if cfg.get("license"):
        topics.append(cfg["license"].lower().replace(".", "-"))
    topics = topics[:10]

    content = f"""#!/usr/bin/env bash
# Generated by iw-oss-publish on {ctx.repo.head_sha[:12] or "unknown"}
# Target: {org}/{repo}
#
# Runs gh CLI commands to flip visibility, configure settings, and enable
# GitHub-native security features.
#
# EVERY destructive step prompts for confirmation.
# Re-runnable: every command is idempotent.

set -euo pipefail
ORG="{org}"
REPO="{repo}"

if ! command -v gh >/dev/null 2>&1; then
  echo "error: gh CLI not installed" >&2; exit 1
fi
gh auth status >/dev/null 2>&1 || {{ echo "error: run 'gh auth login' first" >&2; exit 1; }}

confirm() {{
  read -p "$1 [y/N] " -n 1 -r; echo
  [[ $REPLY =~ ^[Yy]$ ]] || {{ echo "  skipped."; return 1; }}
}}

# ---------------------------------------------------------------------------
# 1. Flip to public (IRREVERSIBLE WITHOUT SUPPORT TICKET)
# ---------------------------------------------------------------------------
confirm "Flip $ORG/$REPO to PUBLIC visibility?" && \\
  gh repo edit "$ORG/$REPO" --visibility public --accept-visibility-change-consequences

# ---------------------------------------------------------------------------
# 2. Description, homepage, topics, merge settings
# ---------------------------------------------------------------------------
gh repo edit "$ORG/$REPO" \\
  --description "{desc}" \\
  --homepage "{homepage}" \\
{chr(10).join(f'  --add-topic "{t}" \\\\' for t in topics)}
  --enable-issues \\
  --enable-squash-merge \\
  --enable-merge-commit=false \\
  --delete-branch-on-merge

# ---------------------------------------------------------------------------
# 3. Branch protection on main
# ---------------------------------------------------------------------------
confirm "Apply branch protection to main?" && \\
gh api "repos/$ORG/$REPO/branches/main/protection" \\
  --method PUT \\
  --field required_status_checks='{{"strict":true,"contexts":["dco","compliance"]}}' \\
  --field enforce_admins=true \\
  --field required_pull_request_reviews='{{"required_approving_review_count":1,"require_code_owner_reviews":true,"dismiss_stale_reviews":true}}' \\
  --field allow_deletions=false \\
  --field allow_force_pushes=false \\
  --field restrictions=null

# ---------------------------------------------------------------------------
# 4. Secret scanning + push protection
# ---------------------------------------------------------------------------
gh api "repos/$ORG/$REPO" --method PATCH \\
  --field security_and_analysis='{{"secret_scanning":{{"status":"enabled"}},"secret_scanning_push_protection":{{"status":"enabled"}}}}' \\
  || echo "  (requires Code Security features — verify via the web UI if this errors)"

# ---------------------------------------------------------------------------
# 5. Dependabot alerts + security updates
# ---------------------------------------------------------------------------
gh api "repos/$ORG/$REPO/vulnerability-alerts" --method PUT
gh api "repos/$ORG/$REPO/automated-security-fixes" --method PUT

# ---------------------------------------------------------------------------
# 6. Private Vulnerability Reporting
# ---------------------------------------------------------------------------
gh api "repos/$ORG/$REPO/private-vulnerability-reporting" --method PUT \\
  || echo "  (PVR requires repo admin — verify in Settings → Security)"

# ---------------------------------------------------------------------------
# 7. Reminders (manual)
# ---------------------------------------------------------------------------
cat <<REMINDERS

MANUAL FOLLOW-UPS:

  [ ] Install cncf/dco2 GitHub App on the org if not already:
      https://github.com/apps/dco

  [ ] Run USPTO and WIPO trademark searches for "{cfg.get("project_name", "")}":
      https://tmsearch.uspto.gov/
      https://branddb.wipo.int/

  [ ] Tag first release (if you haven't already):
      git tag -s v0.1.0 -m 'Initial public release'
      git push origin v0.1.0
      gh release create v0.1.0 --generate-notes

  [ ] Add OpenSSF Scorecard badge to README (after the first scorecard run):
      https://api.securityscorecards.dev/projects/github.com/$ORG/$REPO/badge

{
        '''  [ ] IMPORTANT — open a GitHub Support ticket to purge cached commit SHAs
      (required after history rewrite): https://support.github.com/contact
      Category: "Sensitive data in a repository"
'''
        if has_history_rewrite
        else ""
    }
REMINDERS

echo ""
echo "Playbook complete. Verify settings with:"
echo "  gh repo view $ORG/$REPO --web"
"""
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    return path


# ---------------------------------------------------------------------------
# Checklist
# ---------------------------------------------------------------------------


def write_publish_checklist(
    ctx: Context,
    blockers: list[Finding],
    history_strategy_suggested: str,
    history_secrets: int,
    artifacts: dict[str, Path],
) -> Path:
    cfg = ctx.config
    parsed = parse_github_remote(ctx.repo.remote_url)
    org_repo = (
        "/".join(parsed)
        if parsed
        else f"{cfg.get('company_github_org', '?')}/{cfg.get('project_name', '?')}"
    )

    lines = [
        f"# Publish Checklist — {cfg.get('project_name', '(unnamed)')}",
        "",
        f"**Target:** `{org_repo}`",
        f"**Current HEAD:** `{ctx.repo.head_sha[:12] or 'unknown'}`",
        f"**Current visibility:** `{ctx.repo.visibility}`",
        f"**License:** `{cfg.get('license', 'unset')}`",
        "",
        "---",
        "",
    ]

    if blockers:
        lines.append("## ❌ Blocked — address these BEFORE publishing")
        lines.append("")
        for f in blockers:
            lines.append(f"- [ ] **{f.id}** — {f.summary}")
            if f.remediation:
                lines.append(f"  - {f.remediation}")
        lines.append("")
        lines.append(
            "Run `iw-oss-publish make_oss` first, or address each blocker manually, "
            "then re-run `iw-oss-publish publish`."
        )
        lines.append("")
    else:
        lines.append("## ✅ Pre-flight clean")
        lines.append("")
        lines.append("No MUST-level findings. You can proceed.")
        lines.append("")

    lines.extend(
        [
            "## Step 1 — Choose history strategy",
            "",
            f"**Suggested:** `{history_strategy_suggested}` — see `references/history_rewrite.md` for the decision tree.",
            "",
            "Available strategies:",
            "",
            "- **NUKE** (`.iw/history-rewrite-nuke.sh`): fresh squashed init commit. Zero history preserved. Simplest and safest when history has no consumer value.",
            "- **FILTER-REPO** (`.iw/history-rewrite-filter-repo.sh`): surgical removal of specific files/strings/authors; preserves commit graph. Edit the script's PATHS_TO_PURGE and REPLACEMENTS arrays before running.",
            "- **PRESERVE**: publish history as-is. Only appropriate when secrets scan is clean and no internal references were committed.",
            "",
        ]
    )

    if history_secrets > 0:
        lines.append(
            f"⚠  `gitleaks` found **{history_secrets} secret finding(s) in history** — "
            "PRESERVE is NOT an option. Use NUKE or FILTER-REPO."
        )
        lines.append("")

    lines.extend(
        [
            "## Step 2 — Run the chosen history-rewrite script",
            "",
            "```bash",
            "# Pick ONE:",
            "bash .iw/history-rewrite-nuke.sh",
            "# or",
            "bash .iw/history-rewrite-filter-repo.sh   # edit the arrays first",
            "```",
            "",
            "Each script prompts before doing anything destructive.",
            "",
            "## Step 3 — Re-verify after rewrite",
            "",
            "```bash",
            "python3 .claude/skills/iw-oss-publish/scripts/scan.py",
            "```",
            "",
            "This catches any secrets that survived the rewrite. If MUST findings appear, stop.",
            "",
            "## Step 4 — Flip to public + harden settings",
            "",
            "```bash",
            "bash .iw/publish-playbook.sh",
            "```",
            "",
            "The playbook prompts before the visibility flip and branch-protection apply.",
            "",
            "## Step 5 — Post-publish manual follow-ups",
            "",
            "- [ ] Install `cncf/dco2` GitHub App on the org (if not already) → https://github.com/apps/dco",
            "- [ ] Run USPTO Trademark Search → https://tmsearch.uspto.gov/",
            "- [ ] Run WIPO Global Brand Database search → https://branddb.wipo.int/",
            "- [ ] Tag first release if none exists (`git tag -s v0.1.0 …`)",
            "- [ ] Add OpenSSF Scorecard badge to README after first run",
        ]
    )
    if history_secrets > 0:
        lines.append(
            "- [ ] **Open a GitHub Support ticket** to purge cached commit SHAs after history rewrite "
            "→ https://support.github.com/contact (category: *Sensitive data in a repository*)"
        )
    lines.append("")

    lines.extend(
        [
            "---",
            "",
            "## Artifacts",
            "",
        ]
    )
    for name, p in artifacts.items():
        lines.append(f"- `{p.relative_to(ctx.target)}` — {name}")
    lines.append("")

    path = ctx.iw_dir / "publish-checklist.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Strategy hint
# ---------------------------------------------------------------------------


def suggest_history_strategy(
    history_secrets: int,
    non_noreply_emails: int,
    large_blobs: int,
    pre_existing_strategy: str | None,
) -> str:
    """Return 'nuke' | 'filter-repo' | 'preserve' based on findings."""
    if pre_existing_strategy:
        return pre_existing_strategy
    # Widespread contamination → nuke
    if history_secrets > 20:
        return "nuke"
    # Localized issues → filter-repo
    if history_secrets > 0 or non_noreply_emails > 0 or large_blobs > 0:
        return "filter-repo"
    return "preserve"
